export const runtime = "nodejs";

import { db } from "@/lib/db/client";
import { projects, automationScripts, testCases, sitePages } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import JSZip from "jszip";
import type { TestDataSet } from "@/lib/db/schema";

export async function GET(
  req: Request,
  { params }: { params: Promise<{ projectId: string }> }
) {
  const { projectId } = await params;
  const url = new URL(req.url);
  const mode = url.searchParams.get("mode") ?? "framework"; // "flat" | "framework"

  const [project] = await db.select().from(projects).where(eq(projects.id, projectId));
  if (!project) {
    return new Response(JSON.stringify({ error: "Project not found" }), {
      status: 404, headers: { "Content-Type": "application/json" },
    });
  }

  const scripts = await db.select().from(automationScripts).where(eq(automationScripts.projectId, projectId));
  if (scripts.length === 0) {
    return new Response(JSON.stringify({ error: "No scripts found" }), {
      status: 404, headers: { "Content-Type": "application/json" },
    });
  }

  const cases = await db.select().from(testCases).where(eq(testCases.projectId, projectId));
  const pages = await db.select().from(sitePages).where(eq(sitePages.projectId, projectId));

  const zip = new JSZip();

  if (mode === "flat") {
    // Legacy: flat zip of individual script files
    for (const s of scripts) {
      zip.file(s.fileName, s.code);
    }
  } else {
    // Full Playwright framework with POM structure
    const root = zip.folder("klyron-tests")!;

    // ── playwright.config.js ─────────────────────────────────────────────────
    root.file("playwright.config.js", `const { defineConfig, devices } = require('@playwright/test');

module.exports = defineConfig({
  testDir: './tests',
  timeout: 30000,
  retries: 1,
  fullyParallel: false,
  reporter: [
    ['html', { open: 'never', outputFolder: 'playwright-report' }],
    ['list'],
  ],
  use: {
    baseURL: '${project.targetUrl}',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    trace: 'on-first-retry',
  },
  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
    { name: 'firefox',  use: { ...devices['Desktop Firefox'] } },
    { name: 'webkit',   use: { ...devices['Desktop Safari'] } },
  ],
  outputDir: 'test-results',
});
`);

    // ── package.json ─────────────────────────────────────────────────────────
    root.file("package.json", JSON.stringify({
      name: `klyron-tests-${project.name.toLowerCase().replace(/\s+/g, "-")}`,
      version: "1.0.0",
      private: true,
      scripts: {
        test: "playwright test",
        "test:chromium": "playwright test --project=chromium",
        "test:firefox": "playwright test --project=firefox",
        "test:headed": "playwright test --headed",
        "test:report": "playwright show-report",
        "test:debug": "playwright test --debug",
      },
      devDependencies: {
        "@playwright/test": "^1.44.0",
      },
    }, null, 2));

    // ── README.md ─────────────────────────────────────────────────────────────
    root.file("README.md", `# ${project.name} — Klyron Test Suite

Generated by [Klyron](https://github.com/KaarimHussain/Klyron-AI-Agent-Testing-Framework)

## Setup

\`\`\`bash
npm install
npx playwright install
\`\`\`

## Run tests

| Command | Description |
|---|---|
| \`npm test\` | Run all tests (all browsers) |
| \`npm run test:chromium\` | Chrome only |
| \`npm run test:firefox\` | Firefox only |
| \`npm run test:headed\` | Headed mode (visible browser) |
| \`npm run test:debug\` | Debug mode with Playwright Inspector |
| \`npm run test:report\` | Open last HTML report |

## Structure

\`\`\`
klyron-tests/
├── playwright.config.js   # Config: browsers, retries, reporters
├── tests/                 # Generated spec files (${scripts.length} tests)
├── pages/                 # Page Object Model base classes
├── utils/                 # Shared helpers and test data
└── test-results/          # Screenshots, videos, traces (git-ignored)
\`\`\`

## Target site

**URL:** ${project.targetUrl}
**Pages crawled:** ${pages.length}
**Test cases:** ${cases.length}
`);

    // ── .gitignore ────────────────────────────────────────────────────────────
    root.file(".gitignore", `node_modules/
test-results/
playwright-report/
`);

    // ── pages/BasePage.js ─────────────────────────────────────────────────────
    const pagesFolder = root.folder("pages")!;
    pagesFolder.file("BasePage.js", `/**
 * BasePage — shared helpers for all page objects.
 */
class BasePage {
  constructor(page) {
    this.page = page;
    this.baseURL = '${project.targetUrl}';
  }

  async navigate(path = '/') {
    await this.page.goto(this.baseURL + path);
    await this.page.waitForLoadState('networkidle');
  }

  async waitForElement(selector, timeout = 10000) {
    await this.page.waitForSelector(selector, { state: 'visible', timeout });
  }

  async fillField(selector, value) {
    await this.page.locator(selector).fill(value);
  }

  async clickElement(selector) {
    await this.page.locator(selector).click();
  }

  async getText(selector) {
    return this.page.locator(selector).textContent();
  }

  async isVisible(selector) {
    return this.page.locator(selector).isVisible();
  }

  async takeScreenshot(name) {
    await this.page.screenshot({
      path: \`test-results/\${name}-\${Date.now()}.png\`,
      fullPage: true,
    });
  }
}

module.exports = { BasePage };
`);

    // Generate a page object per crawled page
    for (const p of pages) {
      const pageName = new URL(p.url).pathname
        .replace(/^\//, "").replace(/\//g, "-").replace(/[^a-zA-Z0-9-]/g, "") || "HomePage";
      const className = pageName
        .split("-")
        .map((w: string) => w.charAt(0).toUpperCase() + w.slice(1))
        .join("") + "Page";

      const forms = (p.forms as { selector: string; fields: { name: string; type: string; label: string; selector: string }[] }[] | null) ?? [];
      const elements = (p.interactiveElements as { type: string; text: string; selector: string }[] | null) ?? [];

      const selectorLines = [
        ...forms.flatMap((f) =>
          f.fields.map((field) =>
            `    this.${field.name.replace(/[^a-zA-Z0-9]/g, "_")} = page.locator('${field.selector}');`
          )
        ),
        ...elements.slice(0, 10).map((el) => {
          const name = el.text.toLowerCase().replace(/[^a-zA-Z0-9]/g, "_").replace(/_+/g, "_").slice(0, 30);
          return `    this.${name || el.type + "_element"} = page.locator('${el.selector}');`;
        }),
      ].join("\n");

      pagesFolder.file(`${className}.js`, `const { BasePage } = require('./BasePage');

class ${className} extends BasePage {
  constructor(page) {
    super(page);
    // Selectors for: ${p.url}
${selectorLines || "    // No specific selectors detected for this page"}
  }
}

module.exports = { ${className} };
`);
    }

    // ── utils/helpers.js ──────────────────────────────────────────────────────
    const utilsFolder = root.folder("utils")!;
    utilsFolder.file("helpers.js", `/**
 * Shared test helpers.
 */

/**
 * Attempt to log in using common selector patterns.
 * @param {import('@playwright/test').Page} page
 * @param {string} username
 * @param {string} password
 */
async function login(page, username, password) {
  const usernameSelectors = [
    'input[name="username"]', 'input[name="email"]',
    'input[type="email"]', '#username', '#email',
  ];
  for (const sel of usernameSelectors) {
    const el = page.locator(sel).first();
    if (await el.isVisible({ timeout: 2000 }).catch(() => false)) {
      await el.fill(username);
      break;
    }
  }
  await page.locator('input[type="password"]').first().fill(password);
  const submitSel = ['button[type="submit"]', 'input[type="submit"]'];
  for (const sel of submitSel) {
    const el = page.locator(sel).first();
    if (await el.isVisible({ timeout: 1000 }).catch(() => false)) {
      await el.click();
      await page.waitForTimeout(2000);
      return;
    }
  }
  await page.keyboard.press('Enter');
  await page.waitForTimeout(2000);
}

/**
 * Wait for a navigation or network idle after an action.
 * @param {import('@playwright/test').Page} page
 */
async function waitForPageReady(page) {
  await page.waitForLoadState('networkidle', { timeout: 15000 });
}

module.exports = { login, waitForPageReady };
`);

    // ── utils/testData.js ────────────────────────────────────────────────────
    const allTestData: Record<string, TestDataSet[]> = {};
    for (const tc of cases) {
      const td = tc.testData as TestDataSet[] | null;
      if (td?.length) {
        allTestData[tc.title] = td;
      }
    }

    utilsFolder.file("testData.js", `/**
 * Auto-generated test data for all test cases.
 * Each key is the test case title; value is an array of datasets.
 */
const testData = ${JSON.stringify(allTestData, null, 2)};

module.exports = { testData };
`);

    // ── tests/ ────────────────────────────────────────────────────────────────
    const testsFolder = root.folder("tests")!;
    for (const s of scripts) {
      // Inject a header comment referencing utils
      const withHeader = `// Generated by Klyron | klyron-tests framework
// Helpers: require('../utils/helpers')
// Test data: require('../utils/testData')

${s.code}`;
      testsFolder.file(s.fileName, withHeader);
    }
  }

  const zipBytes = await zip.generateAsync({ type: "uint8array" });
  const zipBuffer = zipBytes.buffer.slice(
    zipBytes.byteOffset,
    zipBytes.byteOffset + zipBytes.byteLength
  );

  const fileName = mode === "flat"
    ? `klyron-scripts-${projectId}.zip`
    : `klyron-framework-${project.name.toLowerCase().replace(/\s+/g, "-")}.zip`;

  return new Response(zipBuffer as ArrayBuffer, {
    headers: {
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="${fileName}"`,
    },
  });
}
